import { Template } from '../../types';

export const TEMPLATES: Template[] = [
  {
    id: 'template-noticia-portal',
    name: 'Notícia Editorial',
    category: 'NOTÍCIA',
    supportedFormats: ['4:5', '1:1', '9:16', '16:9'],
    description: 'Estilo editorial para jornais e portais. Gradiente escuro no rodapé, categoria destacada e leitura nítida.',
    thumbnailGradient: 'from-blue-600 to-slate-900',
    style: {
      layout: 'editorial-bottom',
      titleAlign: 'left',
      overlayType: 'gradient-bottom',
      overlayOpacity: 0.85,
      badgeStyle: 'pill',
      badgeColor: '#2563EB',
      footerStyle: 'clean-line',
      animation: {
        type: 'slide-up',
        duration: 3,
      },
    },
  },
  {
    id: 'template-urgente-breaking',
    name: 'Urgente / Breaking News',
    category: 'URGENTE',
    supportedFormats: ['4:5', '1:1', '9:16', '16:9'],
    description: 'Tarja vermelha de alerta para acontecimentos imediatos e comunicados de última hora.',
    thumbnailGradient: 'from-red-600 to-rose-950',
    style: {
      layout: 'breaking-urgent',
      titleAlign: 'left',
      overlayType: 'solid-bar',
      overlayOpacity: 0.95,
      badgeStyle: 'banner',
      badgeColor: '#DC2626',
      footerStyle: 'dark-bar',
      accentColor: '#EF4444',
      animation: {
        type: 'ticker',
        duration: 4,
      },
    },
  },
  {
    id: 'template-desporto-impact',
    name: 'Desporto Impacto',
    category: 'DESPORTO',
    supportedFormats: ['4:5', '1:1', '9:16', '16:9'],
    description: 'Design dinâmico para futebol, basquetebol e competições com tipografia forte e cores da marca.',
    thumbnailGradient: 'from-emerald-600 to-slate-900',
    style: {
      layout: 'sports-bold',
      titleAlign: 'left',
      overlayType: 'gradient-bottom',
      overlayOpacity: 0.88,
      badgeStyle: 'filled',
      badgeColor: '#059669',
      footerStyle: 'brand-bar',
      accentColor: '#10B981',
      animation: {
        type: 'zoom-in',
        duration: 3,
      },
    },
  },
  {
    id: 'template-ao-vivo-stream',
    name: 'Transmissão Ao Vivo',
    category: 'AO VIVO',
    supportedFormats: ['9:16', '16:9', '4:5', '1:1'],
    description: 'Indicador visual em tempo real para transmissões, coberturas no local e eventos presenciais.',
    thumbnailGradient: 'from-rose-600 to-indigo-950',
    style: {
      layout: 'editorial-bottom',
      titleAlign: 'left',
      overlayType: 'gradient-bottom',
      overlayOpacity: 0.82,
      badgeStyle: 'pill',
      badgeColor: '#E11D48',
      footerStyle: 'clean-line',
      accentColor: '#F43F5E',
      animation: {
        type: 'fade',
        duration: 3,
      },
    },
  },
  {
    id: 'template-curiosidade-card',
    name: 'Curiosidade / Sabia Que?',
    category: 'CURIOSIDADE',
    supportedFormats: ['4:5', '1:1', '9:16'],
    description: 'Formato de cartão flutuante para fatos interessantes, curiosidades científicas e curiosidades gerais.',
    thumbnailGradient: 'from-amber-500 to-stone-900',
    style: {
      layout: 'modern-card',
      titleAlign: 'center',
      overlayType: 'card-floating',
      overlayOpacity: 0.92,
      badgeStyle: 'pill',
      badgeColor: '#D97706',
      footerStyle: 'floating-pill',
      accentColor: '#F59E0B',
      animation: {
        type: 'slide-up',
        duration: 3.5,
      },
    },
  },
  {
    id: 'template-entrevista-quote',
    name: 'Entrevista / Declaração',
    category: 'ENTREVISTA',
    supportedFormats: ['4:5', '1:1', '16:9', '9:16'],
    description: 'Aspas tipográficas refinadas para frases marcantes, entrevistas exclusivas e depoimentos.',
    thumbnailGradient: 'from-blue-700 to-slate-900',
    style: {
      layout: 'quote-interview',
      titleAlign: 'left',
      overlayType: 'gradient-bottom',
      overlayOpacity: 0.85,
      badgeStyle: 'outline',
      badgeColor: '#3B82F6',
      footerStyle: 'clean-line',
      animation: {
        type: 'fade',
        duration: 4,
      },
    },
  },
  {
    id: 'template-anuncio-institucional',
    name: 'Anúncio Institucional',
    category: 'ANÚNCIO',
    supportedFormats: ['4:5', '1:1', '9:16', '16:9'],
    description: 'Comunicação limpa para empresas, comunicados oficiais, editais e órgãos públicos.',
    thumbnailGradient: 'from-sky-600 to-blue-900',
    style: {
      layout: 'minimal-banner',
      titleAlign: 'left',
      overlayType: 'gradient-bottom',
      overlayOpacity: 0.8,
      badgeStyle: 'filled',
      badgeColor: '#0284C7',
      footerStyle: 'brand-bar',
      animation: {
        type: 'slide-up',
        duration: 3,
      },
    },
  },
  {
    id: 'template-evento-agenda',
    name: 'Evento & Agenda',
    category: 'EVENTO',
    supportedFormats: ['4:5', '1:1', '9:16'],
    description: 'Destaque visual de data, hora e local para concertos, conferências, encontros e workshops.',
    thumbnailGradient: 'from-violet-600 to-slate-900',
    style: {
      layout: 'modern-card',
      titleAlign: 'left',
      overlayType: 'card-floating',
      overlayOpacity: 0.9,
      badgeStyle: 'pill',
      badgeColor: '#7C3AED',
      footerStyle: 'clean-line',
      accentColor: '#8B5CF6',
      animation: {
        type: 'zoom-in',
        duration: 3,
      },
    },
  },
  {
    id: 'template-promocao-oferta',
    name: 'Promoção & Oferta',
    category: 'PROMOÇÃO',
    supportedFormats: ['4:5', '1:1', '9:16'],
    description: 'Perfeito para comércio, serviços e promoções relâmpago com chamadas para ação objetivas.',
    thumbnailGradient: 'from-orange-500 to-red-700',
    style: {
      layout: 'breaking-urgent',
      titleAlign: 'center',
      overlayType: 'solid-bar',
      overlayOpacity: 0.95,
      badgeStyle: 'banner',
      badgeColor: '#EA580C',
      footerStyle: 'brand-bar',
      accentColor: '#F97316',
      animation: {
        type: 'slide-up',
        duration: 3,
      },
    },
  },
];

export const CATEGORIES = [
  'TODOS',
  'NOTÍCIA',
  'DESPORTO',
  'CURIOSIDADE',
  'ANÚNCIO',
  'URGENTE',
  'AO VIVO',
  'ENTREVISTA',
  'EVENTO',
  'PROMOÇÃO',
];
